// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WinvL2myJX8iLRBSnNgn7uD71E2RsdE',
    appId: '1:793991143570:android:0b10f7e38ad88d26b9c64b',
    messagingSenderId: '157596352019',
    projectId: 'fitnesstracker-fe1d3',
    authDomain: 'meridiary-v2.firebaseapp.com',
    storageBucket: 'fitnesstracker-fe1d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WinvL2myJX8iLRBSnNgn7uD71E2RsdE',
    appId: '1:793991143570:android:0b10f7e38ad88d26b9c64b',
    messagingSenderId: '157596352019',
    projectId: 'fitnesstracker-fe1d3',
    storageBucket: 'fitnesstracker-fe1d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIy9pHjdF1OESnCjV6PPq7FaRpxAXvQ7U',
    appId: '1:157596352019:ios:87ad74e6d2c446728609e6',
    messagingSenderId: '157596352019',
    projectId: 'fitnesstracker-fe1d3',
    storageBucket: 'fitnesstracker-fe1d3.appspot.com',
    iosBundleId: 'com.fitness.fitnesstracker_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIy9pHjdF1OESnCjV6PPq7FaRpxAXvQ7U',
    appId: '1:157596352019:ios:87ad74e6d2c446728609e6',
    messagingSenderId: '157596352019',
    projectId: 'fitnesstracker-fe1d3',
    storageBucket: 'fitnesstracker-fe1d3.appspot.com',
    iosBundleId: 'com.example.meridiaryV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_pVZZ-bXd-YWWRkR7gUOMooMQBOyNNP0',
    appId: '1:157596352019:web:7b157c31ee92c4bc8609e6',
    messagingSenderId: '157596352019',
    projectId: 'fitnesstracker-fe1d3',
    authDomain: 'meridiary-v2.firebaseapp.com',
    storageBucket: 'fitnesstracker-fe1d3.appspot.com',
  );

}